// Editorial Authority design system — from stitch files
export const colors = {
  surface: "#f9f9fb",
  "surface-container-low": "#f3f3f6",
  "surface-container": "#edeef0",
  "surface-container-high": "#e7e8ea",
  "surface-container-highest": "#e2e2e4",
  "surface-container-lowest": "#ffffff",
  "surface-dim": "#d9dadc",
  "surface-bright": "#f9f9fb",
  "on-surface": "#191c1e",
  "on-surface-variant": "#3f484e",
  "inverse-surface": "#2e3132",
  "inverse-on-surface": "#f0f1f3",
  primary: "#005977",
  "primary-container": "#007398",
  "on-primary": "#ffffff",
  "on-primary-container": "#d7f0ff",
  "primary-fixed": "#c1e8ff",
  "primary-fixed-dim": "#7fd0f9",
  "on-primary-fixed": "#001e2b",
  "on-primary-fixed-variant": "#004d67",
  "inverse-primary": "#7fd0f9",
  secondary: "#9f4200",
  "secondary-container": "#fd7216",
  "on-secondary": "#ffffff",
  "on-secondary-container": "#5a2200",
  "secondary-fixed": "#ffdbcb",
  "secondary-fixed-dim": "#ffb692",
  "on-secondary-fixed": "#341100",
  "on-secondary-fixed-variant": "#793100",
  tertiary: "#515354",
  "tertiary-container": "#696b6c",
  "on-tertiary": "#ffffff",
  "on-tertiary-container": "#ececed",
  "tertiary-fixed": "#e2e2e3",
  "tertiary-fixed-dim": "#c6c6c7",
  "on-tertiary-fixed": "#1a1c1d",
  "on-tertiary-fixed-variant": "#454748",
  outline: "#6f787e",
  "outline-variant": "#bfc8ce",
  error: "#ba1a1a",
  "error-container": "#ffdad6",
  "on-error": "#ffffff",
  "on-error-container": "#93000a",
  background: "#f9f9fb",
  "on-background": "#191c1e",
  "surface-tint": "#006687",
  "surface-variant": "#e2e2e4",
} as const;

export const fontFamily = {
  headline: ["Noto Serif"],
  body: ["Inter"],
  label: ["Work Sans"],
} as const;

export const borderRadius = {
  DEFAULT: "0.125rem",
  lg: "0.25rem",
  xl: "0.5rem",
  full: "0.75rem",
} as const;
